### PR TITLE
Steal bort's Gitlab functionality

### PR DESCRIPTION
**Pull request by mmcclimon**
This steal's bort's mention mr-or-commit in passing. Project shortcuts are gotten from our config repo. (Not committing this directly to master because we probably don't want it until we turn bort's off!)

### CODE REVIEW

**Comment by wolfsage** [comment]
Seems good.

We don't mark an event handled though if we encounter an error trying to handle it? Should we?

**Comment by mmcclimon** [comment]
> We don't mark an event handled though if we encounter an error trying to handle it? Should we?

I don't think so. All that `$event->mark_handled` does (at the moment)  is trigger the 'does not compute' response. In a public channel, we don't want that response, since it's just a mention-in-passing. If it's targeted or in a DM and we don't handle it, we still want "does not compute" so that it's not totally silent.

**Comment by mmcclimon** [comment]
@rjbs Amended and updated!

**Comment by rjbs** [comment]
Applied!  Redundant until Bort is silenced.

**Pull request closed without merging**
