### PR TITLE
Yelling: yell louder, yell harder

### PR DESCRIPTION
**Pull request by mmcclimon**
This is a hilarious, terrible hack so that Synergy will ensure that all
plain text delivered to #yelling is in all caps.

### CODE REVIEW

**Comment by mmcclimon** [comment]
jk, all this does is make the prefix uppercase.

**Comment by mmcclimon** [comment]
Totes updated. No problem can't be solved with more metaprogramming.

**Comment by robn** [comment]
Its funny, because this kind of makes me squeamish in the same way that futzing in the symbol table makes me squeamish. At the same time it doesn't, because this sort of shenanigans is exactly the reason that the MOP exists, and this is so much better anyway because you can choose to modify a single instance of a class rather than the entire world.

So yeah, I like this!

**Comment by mmcclimon** [comment]
Closing this in favor of 6bf84766.

**Pull request closed without merging**
